### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by geekheadxd** [Gryffindor8/Netflix-video-downloader#1]

**Comment by bobdipesh** [comment]
i think script is in development phress, once it complete he will publish, but i want NF tool downloader can you help me to setup private tool

**Comment by geekheadxd** [comment]
I am new to this too . If you have NF account you can use available cracked software to download videos for free !

**Comment by geekheadxd** [comment]
@bobdipesh hello can we talk

**Comment by bobdipesh** [comment]
Yes we can talk and i manage to finished the script and it working now [](https://ibb.co/dLmYZbZ) Text Me in telegram @kir4n1

**Comment by KiranHamal** [comment]
https://ibb.co/dLmYZbZ - Here is a image where you can see its working or not

**Comment by geekheadxd** [comment]
check your telegram ..

**Comment by newdev8** [comment]
Hey @KiranHamal can you send me the script?

**Comment by MG577** [comment]
@KiranHamal can u send me also ?? as I have the NFtool .. but it not working at all

**Comment by techno-arch** [comment]
> @KiranHamal can u send me also ?? as I have the NFtool .. but it not working at all

You got nftool if you dont mind can you send it to me at my discord Techno Arch#1111

**Comment by techno-arch** [comment]
I may be able to help you with it @MG577

**Comment by KiranHamal** [comment]
Guys Tomorrow i will share NF Tool Publicly including Amazon Prime NF tool Hoichoi mxplayer and many More So be excited to get the tool here its a yamaraj tool i belive all you know telly who did piracy of movies, why i am making public is that he took money from too much peoples and provided tool and work sometimes and did not work and do a fraud, i dont have to talk much about him so stay here you will get netflix and what other tool i have all will be share here

**Comment by KiranHamal** [comment]
https://github.com/KiranHamal/NFRipper2.0.1.0 - Guys Go here and donwload Netflix Ripper 2.0.1 will share other tool soon.

**Comment by Sentivet** [comment]
@KiranHamal Can you share jiocinema download tool? If you have please share
